### PR TITLE
VOPlayer improvements

### PR DESCRIPTION
**Pull request by andrewstart**
Adds .pause(), .resume(), .currentPosition, and .currentDuration to VOPlayer.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@andrewstart looks like you have some linting errors. See Travis build fail.

**Comment by andrewstart** [comment]
Psh, closing functions with ) is optional. Syntax errors have been fixed.

**Comment by bigtimebuddy** [comment]
Another thing, could you add jsdocs for `pause` and `resume`? 

Also, I still think an event-based system would be better or a good compliment to the current polling/getter approach you created. What do you think about adding a `start`, `end` and `position` events?

**Comment by andrewstart** [comment]
I've added `start` and `end` events, as those are quite useful for setting up new syncing. SoundJS doesn't have position events, so a polling solution is the only method for updating.

**Comment by bigtimebuddy** [comment]
@andrewstart  Looks good. I tested it with the example. You forgot the `EventDispatcher.call(this)` in the constructor, but I added. Also, I added the currentVO as an event param on the end event too.

**Pull request merged**
