### PR TITLE
Epic/SR-2 - Fall 2024 SpringRoll maintenance

### PR DESCRIPTION
**Pull request by jeremymccurdy-redspace**
SpringRoll 2.7.0 release

- Updated base Node version in nvmrc and workflows to 20
- Dependabot update: Bump follow-redirects from 1.15.2 to 1.15.6
- Bellhop updated to 3.6.0

Ticket: https://pbskids.atlassian.net/browse/SR-12

### CODE REVIEW

**Review by deycorinne — APPROVED** [review]

**Review by 902seanryan — APPROVED** [review]

**Review by TensAndTwenties — APPROVED** [review]

**Comment by jeremymccurdy-redspace** [comment]
Hey folks, I had to re-add 14.x to the node version list in the workflow. The PR wasn't able to merge until that check ran. I'm guessing it's because the workflow on the `main` branch still has 14.x but since it wasn't in the updated workflow it was just hanging.

**Comment by 902seanryan** [comment]
@deycorinne are those checks configured under branch protections? Can you check and see if it can be removed?

**Review by TensAndTwenties — APPROVED** [review]

**Comment by selenaqian** [comment]
Ooh good call I do see it under branch protections. I can remove the 14.x one and add a 20.x one

**Review by 902seanryan — APPROVED** [review]

**Comment by jeremymccurdy-redspace** [comment]
> Branch protections should be updated now!
Thanks @selenaqian I've removed 14.x from the workflow, and it seems to be good now!

**Review by deycorinne — APPROVED** [review]

**Pull request merged**
