### PR TITLE
added custom class to allow for easy use of web workers 

### PR DESCRIPTION
**Pull request by lmckeen**
also updated IE support from 9 to 10

### CODE REVIEW

**Comment by andrewstart** [comment]
We had actually originally had https://github.com/CloudKidStudio/Worker in SpringRoll, but removed it when we decided that it wasn't a core feature for the library. The worker above functions as a fallback even for older browsers. That said, I can see some use to expanding our `Worker.init()` to include some of your functionality here (I didn't realize `Function.prototype.toString()` was a thing!).

**Comment by bigtimebuddy** [comment]
I believe that Workers should not be a core feature to SpringRoll except maybe if there are internal performance advantages that other modules could benefit from. 

SpringRoll is about creating flexible, portable, educational games and should be easy for other 3rd-party libraries to plug-n-play. There's a handful of functionality that falls into a "convenience" bucket, like Buttons or Drag management.  We tried to restrict the convenience stuff to features that would be needed universally. I would consider Workers much like a physic engine: it's nice-to-have, but would not be used in every SpringRoll game and would bloat the library and provide maintenance challenges. There are many JS libraries for dealing with Workers, if your game needs it include one of those libraries with Bower/NPM. Or develop this Worker implementation into an external library.

**Comment by yanshcherbakovatredspace** [comment]
@bigtimebuddy You're exactly right. Workers should only be in the core if the core functions have a performance benefit from Workers. This is actually what we're trying to achieve. We've found major performance improvements on game level using Workers, and have been testing to see if we can improve the internal performance in the core, or across Springroll.

At this point we're only introducing the ability to have Workers available as we are still testing if there's a substantial performance benefit.

Otherwise, as you said, Workers would be added as plugin, separate library or implemented on the game level much like a physics library.

Maybe, until we are able to demonstrate a major improvement in internal performance using Workers, this should stay in the branch before merging into master and making it available.

**Comment by yanshcherbakovatredspace** [comment]
Closing this pull request for now. This pull request will be re-opened when we are able to provide a demonstration of internal performance improvements.

**Pull request closed without merging**
