### PR TITLE
Fix caption typings

### PR DESCRIPTION
**Pull request by ericente**
Recent changes to some caption-related typings are incorrect and break compiling in projects targeting previous versions of SpringRoll. These are more accurate.

Side note that I noticed while working on these: `DOMRenderer` accepts a `templateVariables` argument in its constructor, but each time `start()` is called, the previously-set `templateVariables` will be overwritten (or removed if no new `templateVariables` object is provided).

Another side note: It looks like it's possible for the default values for Application.state to override initial settings from the Container.

### CODE REVIEW

**Review by 902seanryan — DISMISSED** [review]

**Comment by 902seanryan** [comment]
@ericente The changes look good to me, but would you be able to push up an empty commit? The checks didn't trigger properly.

**Comment by ericente** [comment]
@902seanryan, this still seems to not be building. Not sure if it's because the PR is from a fork, or because these files don't affect build output.

**Comment by 902seanryan** [comment]
> @902seanryan, this still seems to not be building. Not sure if it's because the PR is from a fork, or because these files don't affect build output.

The typings files are excluded from the actions it turns out. I'm gonna see if there's a way to force it.

**Comment by 902seanryan** [comment]
@ericente Sorry this is taking so long, we're looking at adding a fix to avoid this issue in the future. But for now, if you could just go make a change to the readme (add a space, a line, whatever) that should trigger the build and we can get this merged.

**Review by 902seanryan — DISMISSED** [review]

**Review by 902seanryan — APPROVED** [review]

**Pull request merged**
