### PR TITLE
Updated SoundInstance's channel pausing for SoundJS 0.6.4

### PR DESCRIPTION
**Pull request by probityrules**
While working with the SpringRoll/SoundJS master branch, I realized that `pause()` and `resume()` in `AbstractSoundInstance` have been deprecated and removed in SoundJS 0.6.4, causing audio to keep running when a SpringRoll game loses focus. I've updated SpringRoll's `SoundInstance` to toggle the `AbstractSoundInstance`'s `paused` property instead.

This change works for both [the SoundJS 0.6.3 release](https://github.com/SpringRoll/SoundJS/releases/tag/0.6.3) and the master branch's SoundJS 0.6.4 yet to be released.

### CODE REVIEW

**Comment by yanshcherbakovatredspace** [comment]
Sorry for the delay. The CI tests failed because it is pulling QUnit version 2, which we currently upgrading to. Checked locally, all tests pass.

@probityrules Could you run `grunt build test` and commit the build files as well? Thanks!

**Comment by probityrules** [comment]
Sure, I committed the two modules that have changed: "Sound" from this PR and "Container Client" from PR https://github.com/SpringRoll/SpringRoll/pull/106.

**Comment by yanshcherbakovatredspace** [comment]
Looks good to me.

**Comment by bigtimebuddy** [comment]
Looks good to me.

**Pull request merged**
