### PR TITLE
Release/2.4.3

### PR DESCRIPTION
**Pull request by selenaqian**

### CODE REVIEW

**Review by 902seanryan — CHANGES_REQUESTED** [review]
Make sure the versions in package.json and package.lock.json are updated to 2.4.3 as well

**Comment by 902seanryan** [comment]
@selenaqian @deycorinne should we sneak the brand new dependabot PR in to this one? It opened two hours ago, might be worth just merging into this release branch

**Comment by selenaqian** [comment]
> @selenaqian @deycorinne should we sneak the brand new dependabot PR in to this one? It opened two hours ago, might be worth just merging into this release branch

Yeah I did see that opened. Will defer to @deycorinne but happy to go and add that in too

**Review by deycorinne — APPROVED** [review]

**Comment by deycorinne** [comment]
> > @selenaqian @deycorinne should we sneak the brand new dependabot PR in to this one? It opened two hours ago, might be worth just merging into this release branch
> 
> Yeah I did see that opened. Will defer to @deycorinne but happy to go and add that in too

yesss go for it!

**Comment by 902seanryan** [comment]
@selenaqian remember to re-run the build in case the dependencies need to be pulled into the build

**Review by 902seanryan — APPROVED** [review]

**Review by deycorinne — APPROVED** [review]

**Pull request merged**
